name: Terraform and Terratest Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Choose your desired AWS region

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.0  # Specify the Terraform version you need

    - name: Cache Terraform init
      uses: actions/cache@v2
      with:
        path: ~/.terraform
        key: ${{ runner.os }}-terraform-${{ hashFiles('**/*.tf') }}
        restore-keys: |
          ${{ runner.os }}-terraform-

    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y curl
        curl -sL https://github.com/gruntwork-io/terratest/releases/download/v0.39.0/terratest-linux-amd64 -o terratest
        chmod +x terratest
        sudo mv terratest /usr/local/bin

    - name: Terraform Init
      run: | 
        cd s3
        terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve

  terratest:
    name: Run Terratest
    runs-on: ubuntu-latest
    needs: terraform

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.18'  # Specify the Go version needed for Terratest

    - name: Install dependencies
      run: |
        go mod tidy
        go get github.com/gruntwork-io/terratest/modules/terraform
        go get github.com/stretchr/testify/assert

    - name: Run Terratest
      run: |
        cd test
        go test -v
